=== Juanc-Torres/Juanc-Torres.github.io/.astro/collections/staticData.schema.json
{
  "$ref": "#/definitions/staticData",
  "definitions": {
    "staticData": {
      "type": "object",
      "properties": {
        "profileImage": {
          "type": "string"
        },
        "profileAlt": {
          "type": "string"
        },
        "profileLink": {
          "type": "string"
        },
        "profileTitle": {
          "type": "string"
        },
        "profileName": {
          "type": "string"
        },
        "github": {
          "type": "string",
          "format": "uri"
        },
        "linkedin": {
          "type": "string",
          "format": "uri"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "alias": {
          "type": "string"
        },
        "githubIconName": {
          "type": "string"
        },
        "linkedinIconName": {
          "type": "string"
        },
        "emailIconName": {
          "type": "string"
        },
        "portfolioImage": {
          "type": "string"
        },
        "contactSectionTitle": {
          "type": "string"
        },
        "contactSectionSubtitle": {
          "type": "string"
        },
        "contactSectionButtonText": {
          "type": "string"
        },
        "contactSectionButtonIcon": {
          "type": "string"
        },
        "techsTitle": {
          "type": "string"
        },
        "hobbies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "profileImage",
        "profileAlt",
        "profileLink",
        "profileTitle",
        "profileName",
        "github",
        "linkedin",
        "email",
        "alias",
        "githubIconName",
        "linkedinIconName",
        "emailIconName",
        "portfolioImage",
        "contactSectionTitle",
        "contactSectionSubtitle",
        "contactSectionButtonText",
        "contactSectionButtonIcon",
        "techsTitle",
        "hobbies"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Juanc-Torres/Juanc-Torres.github.io/src/content/staticData/allStaticData.json
{
  "profileImage": "/images/jc.jpg",
  "profileAlt": "Foto de Juan Carlos Torres",
  "profileLink": "/#home",
  "profileTitle": "Full Stack Web Developer",
  "profileName": "Juan Carlos Torres",

  "github": "https://github.com/Juanc-Torres",
  "linkedin": "https://www.linkedin.com/in/jc-torres-rodriguez/",
  "email": "jc.torres.rodriguez00@gmail.com",

  "alias": "Juanc-Torres",

  "portfolioImage": "/images/portfolio.webp",

  "contactSectionTitle": "¿Tienes alguna pregunta?",
  "contactSectionSubtitle": "No dudes en hablarme",
  "contactSectionButtonText": "Contactar",
  "contactSectionButtonIcon": "paperplane",

  "techsTitle": "Tecnologías",

  "githubIconName": "github",
  "linkedinIconName": "linkedin",
  "emailIconName": "envelope",

  "hobbies": [
    "Senderismo",
    "Buceo",
    "Ajedrez",
    "Cine",
    "Viajar",
    "Podcast"
  ]
}
